### ISSUE TITLE
Document which boards are supported

### ISSUE THREAD

**Issue by oveddan** [adafruit/Adafruit_DotStar#14]
I, for example, want to use this on the beaglebone.  Is it supported there?

It would be great if at a minimum the readme said which platforms are supported.

**Comment by caternuson** [comment]
Unfortunately, this kind of information is nearly impossible to provide completely and also maintain current. The learn guide covers general usage requirements:
https://learn.adafruit.com/adafruit-dotstar-leds

Closing since not a library code issue.
