### ISSUE TITLE
Set SPI clock to 8Mhz on chipKIT (PIC32) by default

### ISSUE THREAD

**Issue by EmbeddedMan** [adafruit/Adafruit_DotStar#16]
Currently it gets set to about 750Khz. Use beginTransaction/endTransaction calls to set speed for all PIC32s to 8Mhz, so that it matches the default speed on other supported cores (ESP8266, AVR, Teensy, etc.)

**Comment by caternuson** [comment]
Closing. This seems to have been fixed by #17 at the time of the issue.
