### ISSUE TITLE
Define "Color" method as static

### ISSUE THREAD

**Issue by yngndrw** [adafruit/Adafruit_DotStar#18]
The "Color" helper method should be defined as static as it does not use any member variables:
https://github.com/adafruit/Adafruit_DotStar/blob/master/Adafruit_DotStar.h#L56
https://github.com/adafruit/Adafruit_DotStar/blob/master/Adafruit_DotStar.cpp#L306

This would also match the definition within the NeoPixel library:
https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.h#L143

Also it should be spelt "Colour". :)

**Comment by yngndrw** [comment]
See PR #21.

**Comment by caternuson** [comment]
Closing. Looks like this was taken care of at some point in another PR or commit.
