### ISSUE TITLE
Missing definition for M_PI on Arduino 101

### ISSUE THREAD

**Issue by terbos90803** [adafruit/Adafruit_DotStar#23]
- Arduino board:  101

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.4

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
Install the DotStar library version 1.0.3
Adafruit_DotStar.cpp fails to compile with the error:
<path>\Arduino\libraries\Adafruit_DotStar\Adafruit_DotStar.cpp:356:53: error: 'M_PI' was not declared in this scope

 #define _S1_ (sin((__COUNTER__ - _SBASE_) / 128.0 * M_PI) + 1.0) * 127.5 + 0.5,

Adding a definition for M_PI before this fixes the problem and the library works fine after that.

**Comment by BillyDonahue** [comment]
Was fixed by PR #25. Library no longer references `M_PI`. Can probably close.
