### ISSUE TITLE
Hardware SPI clock divider should be set faster for ItsyBitsy M4

### ISSUE THREAD

**Issue by digitalcircuit** [adafruit/Adafruit_DotStar#31]
## In brief
* The ItsyBitsy M4 appears capable of running the LEDs at a faster rate than currently set
  * Current clock divider: `15` (*`SPI.setClockDivider((F_CPU + 4000000L) / 8000000L);`*)
  * No issues noticed with a clock divider of `1`
* Hardware
  * [Adafruit ItsyBitsy M4 Express](https://www.adafruit.com/product/3800 )
  * 300 DotStar LEDs (2×[5m rolls](https://www.adafruit.com/product/2238?length=5 )) with the [SK9822 chipset](https://cdn-shop.adafruit.com/product-files/2238/SK9822SHIJI.pdf ), connected via [level shifter](https://www.adafruit.com/product/1787 ) to ItsyBitsy M4's `SCK` and `MO` pins
* Software
  * Arduino 1.8.9 IDE on Ubuntu 16.04 64-bit
  * [Adafruit DotStar library `1.1.0`](https://github.com/adafruit/Adafruit_DotStar/releases )

## Details
In experimentation with the ItsyBitsy M4 Express, updating 300 DotStar LEDs from the Arduino takes around `3326 µs`, measured like so:

```cpp
// Set up LED strips first
// [...]
unsigned long start = micros();   // Track start time
strip.show();                     // Refresh strip
Serial.println(micros() - start); // Print time taken
```

However, by setting the SPI clock divider to `1` instead of the default calculated `15`, updating the same 300 LEDs takes around `2518 µs`, averaging `0.8 ms` faster updates.

Changes made for testing:
```diff
--- a/Adafruit_DotStar.cpp
+++ b/Adafruit_DotStar.cpp
@@ -115,7 +115,11 @@ void Adafruit_DotStar::hw_spi_init(void) { // Initialize hardware SPI
     SPI.beginTransaction(SPISettings(8000000, MSBFIRST, SPI_MODE0));
     SPI.endTransaction();
   #else
-    SPI.setClockDivider((F_CPU + 4000000L) / 8000000L); // 8-ish MHz on Due
+    #if defined(ADAFRUIT_ITSYBITSY_M4_EXPRESS)
+      SPI.setClockDivider(1); // As fast as possible
+    #else
+      SPI.setClockDivider((F_CPU + 4000000L) / 8000000L); // 8-ish MHz on Due
+    #endif
   #endif
  #endif
   SPI.setBitOrder(MSBFIRST);
```

### Resolution

Though I can manually override by calling `SPI.setClockDivider(1);` after calling `lights.begin()`, it'd make sense to offer all users of the library the faster update rate.

Are there gotchas or pitfalls that I am overlooking with this approach, and/or can this be done in a more generic way?

---
*In case it's used for automatic bug tagging, I've filled out the original template here:*

- Arduino board:  **ItsyBitsy M4**
- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.9**
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

## Example

**`strandtest_perf.ino`**

```cpp
// Simple strand test for Adafruit Dot Star RGB LED strip.
// Mostly copied from https://github.com/adafruit/Adafruit_DotStar/blob/master/examples/strandtest/strandtest.ino
// Includes commands to measure timing of updating LED strand

#include <Adafruit_DotStar.h>
#include <SPI.h>

// For testing: 300 DotStar pixels
#define NUMPIXELS 300 // Number of LEDs in strip

// For testing: hardware SPI
Adafruit_DotStar strip(NUMPIXELS, DOTSTAR_BGR);

void setup() {
  Serial.begin(115200);     // Initialize to fastest common baud rate

  strip.begin();            // Initialize pins for output
  //SPI.setClockDivider(1); // Override default SPI clock divider
  strip.show();             // Turn all LEDs off ASAP
}

// Runs 10 LEDs at a time along strip, cycling through red, green and blue.

int      head  = 0, tail = -10; // Index of first 'on' and 'off' pixels
uint32_t color = 0xFF0000;      // 'On' color (starts red)

void loop() {
  strip.setPixelColor(head, color); // 'On' pixel at head
  strip.setPixelColor(tail, 0);     // 'Off' pixel at tail

  unsigned long start = micros();   // Track start time
  strip.show();                     // Refresh strip
  Serial.println(micros() - start); // Print time taken

  delay(20);                        // Pause 20 milliseconds (~50 FPS)

  if(++head >= NUMPIXELS) {         // Increment head index.  Off end of strip?
    head = 0;                       //  Yes, reset head index to start
    if((color >>= 8) == 0)          //  Next color (R->G->B) ... past blue now?
      color = 0xFF0000;             //   Yes, reset to red
  }
  if(++tail >= NUMPIXELS) tail = 0; // Increment, reset tail index
}
```

**Comment by ladyada** [comment]
sure, it depends a bit on the board wiring and setup - 1-4MHz is 'safe'

**Comment by digitalcircuit** [comment]
Noted!  Ensuring the out-of-box defaults are reliable in a variety of situations makes sense.  In this case, since changing the SPI clock divider doesn't require library modifications, I'm satisfied with having to override it [in my personal project](https://github.com/digitalcircuit/ActinicArduino ).

Before closing this issue, should this be documented anywhere as a means to get faster refresh rates at one's own risk, e.g. a comment in `Adafruit_DotStar::hw_spi_init()`?

**Comment by ladyada** [comment]
yep a comment is good :) you can submit a PR
