### ISSUE TITLE
fill() function take too long to change

### ISSUE THREAD

**Issue by harryhuynh-x** [adafruit/Adafruit_DotStar#34]
The fill() function doesn't switch fast enough. It seems to have a big delay somewhere, which I couldn't spot. 
My expectation will have a color-switching very fast ~1ms or even slower, but apparently, it would take 100ms or more and can be detected the color change by eyes.  

See the code below: 

import adafruit_dotstar
import digitalio
import board
import math
import time
import random

num_pixels = 40
brightness = 0.005 

pixels = adafruit_dotstar.DotStar(board.SCK, board.MOSI, num_pixels, brightness=brightness, auto_write=False)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

while True:

  pixels.fill(WHITE)
  pixels.show()
  time.sleep(0.001)
  
  pixels.fill(BLACK)
  pixels.show()
  time.sleep(0.001)

**Comment by ladyada** [comment]
hiya this is the arduino library
please post issue on https://github.com/adafruit/Adafruit_CircuitPython_DotStar
thanx :)
