### ISSUE TITLE
Sk9822 Support

### ISSUE THREAD

**Issue by miloit** [adafruit/Adafruit_DotStar#36]
Are the SK9822 version also supported???

Thanks

**Comment by ladyada** [comment]
please try and reopen the issue if it does not work :)

**Comment by miloit** [comment]
It doesn't work for me with SK9822 ada102-c

**Comment by ladyada** [comment]
google says there are some differences perhaps https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/

**Comment by miloit** [comment]
Can I adjust the lib??

**Comment by ladyada** [comment]
yep please try and submit a PR!

**Comment by miloit** [comment]
I can not try it not know what to change

**Comment by ladyada** [comment]
please ask vendor you purchased from to help

**Comment by caternuson** [comment]
Going to close again. Can reopen (again) if more specific information on actual hardware being used is available.
