### ISSUE TITLE
DeprecationWarning: symbol module is deprecated

### ISSUE THREAD

**Issue by wilwet** [adafruit/Adafruit_DotStar#51]
DeprecationWarning: The symbol module is deprecated and will be removed in future versions of Python from symbol import testlist_star_expr.

in version 2.2.5

**Comment by caternuson** [comment]
This repo contains Arduino library source code. Your issue appears to be Python related. How are you using this library in conjunction with Python?

**Comment by wilwet** [comment]
Sorry wrong location for the issue.
