### ISSUE TITLE
DotStar v1.2.2 breaks strandtest hardware SPI on ItsyBitsy M4

### ISSUE THREAD

**Issue by digitalcircuit** [adafruit/Adafruit_DotStar#54]
- Arduino board:  **ItsyBitsy M4 Express**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **2.0.4**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

1.  Connect a strand of DotStar LEDs to the hardware SPI pins on the ItsyBitsy M4 (`SCK` and `MOSI`)
2.  Download the 1.2.1 or 1.2.2 version of the DotStar library
3.  Open and [modify the bundled `strandtest.ino` example to use hardware SPI](https://github.com/adafruit/Adafruit_DotStar/blob/6b8287e96eb19bec79fb702d76597580cd44e113/examples/strandtest/strandtest.ino#L24-L26 ), **not** bit-banging
```diff
diff --git a/strandtest.ino b/strandtest-hardware.ino
index bdf885c..d798ef9 100644
--- a/strandtest.ino
+++ b/strandtest-hardware.ino
@@ -15,7 +15,7 @@
 // Here's how to control the LEDs from any two pins:
 #define DATAPIN    4
 #define CLOCKPIN   5
-Adafruit_DotStar strip(NUMPIXELS, DATAPIN, CLOCKPIN, DOTSTAR_BRG);
+//Adafruit_DotStar strip(NUMPIXELS, DATAPIN, CLOCKPIN, DOTSTAR_BRG);
 // The last parameter is optional -- this is the color data order of the
 // DotStar strip, which has changed over time in different production runs.
 // Your code just uses R,G,B colors, the library then reassigns as needed.
@@ -23,7 +23,7 @@ Adafruit_DotStar strip(NUMPIXELS, DATAPIN, CLOCKPIN, DOTSTAR_BRG);
 
 // Hardware SPI is a little faster, but must be wired to specific pins
 // (Arduino Uno = pin 11 for data, 13 for clock, other boards are different).
-//Adafruit_DotStar strip(NUMPIXELS, DOTSTAR_BRG);
+Adafruit_DotStar strip(NUMPIXELS, DOTSTAR_BRG);
 
 void setup() {

```
4.  Observe the results

With DotStar version 1.2.1, the DotStar LEDs show the strand testing pattern.

With DotStar version 1.2.2, the microcontroller appears to lock up, requiring a double-tap Reset into bootloader to flash new code.

Of note, the ItsyBitsy M4 appears to not have a default `SPI` device defined.  Should `strandtest.ino` be updated?

**Comment by caternuson** [comment]
The preproc logic in this library should be fixed. The current conditional apparently does not work for all cases.

This simple example:
```cpp
void setup() {
  Serial.begin(9600);
  while (!Serial);

#if defined SPI
  Serial.println("SPI found.");
#else
  Serial.println("SPI NOT found.");
#endif
}

void loop() {
}
```

Outputs this in the Serial Monitor:
```
SPI NOT found.
```

As a temporary work around, explicitly passing the hardware SPI reference should work: 
```cpp
Adafruit_DotStar strip(NUMPIXELS, DOTSTAR_BRG, &SPI);
```

**Comment by digitalcircuit** [comment]
@caternuson Thank you!  I've updated the DotStar library here and I can confirm this resolved the issue for me, too.
